raw_data_file: 'data/dataset_credit_risk.csv'
train_data_file: 'data/train_data.csv'
use_pyspark: False # Whether to use pyspark or pandas for preprocessing, use pyspark only with very large dataset on a server machine otherwise pyspark may take longer than pandas for not very large datasets due to overhead